version: '3.8'

services:
  orchestrator:
    container_name: orchestrator
    build:
      context: .
      dockerfile: Dockerfile.Orchestrator
    ports:
      - '8080:8080'
    networks:
      - calc_net

  agent:
    container_name: agent
    build:
      context: .
      dockerfile: Dockerfile.Agent
    ports:
      - '5000:5000'
    networks:
      - calc_net
    depends_on:
     - orchestrator

networks:
  calc_net: 
    