// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/agent.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExpressionRequest struct {
	Expression           string   `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpressionRequest) Reset()         { *m = ExpressionRequest{} }
func (m *ExpressionRequest) String() string { return proto.CompactTextString(m) }
func (*ExpressionRequest) ProtoMessage()    {}
func (*ExpressionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{0}
}

func (m *ExpressionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionRequest.Unmarshal(m, b)
}
func (m *ExpressionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionRequest.Marshal(b, m, deterministic)
}
func (m *ExpressionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionRequest.Merge(m, src)
}
func (m *ExpressionRequest) XXX_Size() int {
	return xxx_messageInfo_ExpressionRequest.Size(m)
}
func (m *ExpressionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionRequest proto.InternalMessageInfo

func (m *ExpressionRequest) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

type ExpressionResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpressionResponse) Reset()         { *m = ExpressionResponse{} }
func (m *ExpressionResponse) String() string { return proto.CompactTextString(m) }
func (*ExpressionResponse) ProtoMessage()    {}
func (*ExpressionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd830a99d5efef4e, []int{1}
}

func (m *ExpressionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionResponse.Unmarshal(m, b)
}
func (m *ExpressionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionResponse.Marshal(b, m, deterministic)
}
func (m *ExpressionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionResponse.Merge(m, src)
}
func (m *ExpressionResponse) XXX_Size() int {
	return xxx_messageInfo_ExpressionResponse.Size(m)
}
func (m *ExpressionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionResponse proto.InternalMessageInfo

func (m *ExpressionResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*ExpressionRequest)(nil), "agent.ExpressionRequest")
	proto.RegisterType((*ExpressionResponse)(nil), "agent.ExpressionResponse")
}

func init() {
	proto.RegisterFile("proto/agent.proto", fileDescriptor_dd830a99d5efef4e)
}

var fileDescriptor_dd830a99d5efef4e = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x4f, 0xcd, 0x2b, 0xd1, 0x03, 0xb3, 0x85, 0x58, 0xc1, 0x1c, 0x25, 0x63,
	0x2e, 0x41, 0xd7, 0x8a, 0x82, 0xa2, 0xd4, 0xe2, 0xe2, 0xcc, 0xfc, 0xbc, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x21, 0x39, 0x2e, 0xae, 0x54, 0xb8, 0xa0, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x92, 0x88, 0x92, 0x0e, 0x97, 0x10, 0xb2, 0xa6, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21,
	0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xb0, 0x0e, 0xc6, 0x20, 0x28, 0xcf, 0x28,
	0x94, 0x4b, 0xd0, 0x39, 0x31, 0x27, 0xb9, 0x34, 0x27, 0xb1, 0x24, 0xbf, 0x28, 0x38, 0xb5, 0xa8,
	0x2c, 0x33, 0x39, 0x55, 0xc8, 0x81, 0x8b, 0x13, 0x26, 0x98, 0x2a, 0x24, 0xa1, 0x07, 0x71, 0x19,
	0x86, 0x4b, 0xa4, 0x24, 0xb1, 0xc8, 0x40, 0xac, 0x73, 0xb2, 0x8c, 0x32, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x29, 0x2d, 0xce, 0xd6, 0x4d, 0xce, 0x48, 0xcc,
	0x4b, 0x4e, 0xcd, 0xc9, 0xc9, 0x2f, 0xd2, 0x4f, 0xc9, 0x2c, 0x2e, 0x29, 0xca, 0x4c, 0x2a, 0x2d,
	0x49, 0x4d, 0x89, 0x4f, 0x86, 0xdb, 0xae, 0x0f, 0xf6, 0x7b, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x40, 0x9f, 0x5c, 0x93, 0x17, 0x01, 0x00, 0x00,
}
